### ISSUE TITLE
Can I use this library for model quantization with only Pytorch+CPU？

### ISSUE THREAD

**Issue by lemon-little** [ModelTC/llmc#1]
Can I use this library for model quantization with only Pytorch+CPU？

**Comment by Harahan** [comment]
I think it is easy to support Pytorch+CPU, since we only use ``*.to(device="cuda:0")`` or other hard code to quantize the model on GPU. So, you can modify the code by yourself or wait for us to improve our code.

**Comment by lemon-little** [comment]
In which directory are *.to(device) and other hard codes concentrated? If I need to modify the code myself to support CPU+pytorch, can you tell me roughly what needs to be changed?

**Comment by Harahan** [comment]
Most of these codes are placed in `llmc/compression/`. I suggest you to modify codes when error happens during runtime or just try words-matching function in your IDE, e.g., vscode.
