### ISSUE TITLE
Inference per layer mode has no support for Llama model

### ISSUE THREAD

**Issue by ZeusXuan** [ModelTC/llmc#115]
[rank0]: Traceback (most recent call last):
[rank0]:   File "//workspace/llmc/llmc/__main__.py", line 242, in <module>
[rank0]:     main(config)
[rank0]:   File "//workspace/llmc/llmc/__main__.py", line 54, in main
[rank0]:     ppl = ppl_eval.eval(model)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//workspace/llmc/llmc/eval/eval_base.py", line 108, in eval
[rank0]:     eval_res = self.eval_func(model_fp, model, self.testenc, self.seq_len, self.bs)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//workspace/llmc/llmc/eval/eval_ppl.py", line 32, in eval_func
[rank0]:     lm_logits = model(inputs).logits
[rank0]:                 ^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
[rank0]:     outputs = self.model(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/transformers/models/llama/modeling_llama.py", line 976, in forward
[rank0]:     position_embeddings = self.rotary_emb(hidden_states, position_ids)
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "//miniconda3/envs/llmc/lib/python3.12/site-packages/transformers/models/llama/modeling_llama.py", line 211, in forward
[rank0]:     freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
[rank0]:              ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[rank0]: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)

How to fix the bug here？

**Comment by ZeusXuan** [comment]
I use the Llama3-8B for AWQ transform,but I find the same error in the both eval and calibration sections. It seems the problem of RMSNorm operation in the file of `/miniconda3/envs/llmc/lib/python3.12/site-packages/transformers/models/llama/modeling_llama.py`

**Comment by gushiqiao** [comment]
> I use the Llama3-8B for AWQ transform,but I find the same error in the both eval and calibration sections. It seems the problem of RMSNorm operation in the file of `/miniconda3/envs/llmc/lib/python3.12/site-packages/transformers/models/llama/modeling_llama.py`

Please try downgrading transformers to version 4.41.2.
