### ISSUE TITLE
llmc可以支持smoothqaunt的w8a8在trt-llm后端推理吗？

### ISSUE THREAD

**Issue by GuangyanZhang** [ModelTC/llmc#136]
export_trtllm.py 量化类型直接指定quant_config.quant_algo = QuantAlgo.W4A16，是否目前还不支持激活的量化呢？

**Comment by gushiqiao** [comment]
@helloyongyang

**Comment by Harahan** [comment]
We don't update the ``export_trtllm.py`` for a long time.
