### ISSUE TITLE
KV cache / post-RoPE rotation & quantization in QuaRot

### ISSUE THREAD

**Issue by sasha-hailo** [ModelTC/llmc#148]
Hello,
First of all, thank you for your effort in creating and sharing this useful repo!

I'm looking into the code of QuaRot implementation.
My apologies in advance if I'm missing something, but I could not find where your code implements rotation and quantization of KV cache (in particular, of post-RoPE K values).
Do you implement this functionality? If yes, could you please point out where it is made?

Thanks in advance!

**Comment by Harahan** [comment]
No，and we do not implement KV cache quantization.

**Comment by sasha-hailo** [comment]
@Harahan, thank you for your response.
Would you like to consider this as a feature request?
I see that you are also in process of implementing **_SpinQuant_** (which is great!), 
and I think that neither QuaRot or SpinQuant support can be complete without this feature.

**Comment by Harahan** [comment]
Sorry, we don't plan to add this feature. You can implement this by yourself.

**Comment by sasha-hailo** [comment]
@Harahan,
Sorry for getting back to this point,
But the LLMC paper (https://arxiv.org/abs/2405.06001) explicitly mentions evaluations of KV cache quantization (Appendix A.4).
How can these results be reproduced?
:)

**Comment by Harahan** [comment]
@sasha-hailo You can follow the TensorRT-LLM tutorial, directly. For that section, we only benchmarked the efficiency test with TensorRT-LLM.
