### ISSUE TITLE
TesseraQ 2-bit Inference for Qwen2-VL-7B-Instruct

### ISSUE THREAD

**Issue by Oehri-Sven** [ModelTC/llmc#247]
Hi everyone,

I am trying to achieve a 2-bit quantization with TesseraQ based on AWQ with Qwen2-VL-Instruct. The issue I face is that I would like to deploy the saved model outside of LLMC (e.g. vLLM, transformers, etc.). Since quantizing to 2-bit precision is not supported by established inference backends like vLLM I am searching for alternative ways to perform the inference. Doing this with HuggingFace’s transformers leads to the following warning due to the additional quantizing parameters:  “Some weights of the model checkpoint at /home/ubuntu/TesseraQ/models/Qwen2VL/transformed_model/ were not used when initializing Qwen2VLForConditionalGeneration: ['model.layers.0.mlp.down_proj.buf_output_scale_factor', 'model.layers.0.mlp.down_proj.buf_qmax', 'model.layers.0.mlp.down_proj.buf_qmin', 'model.layers.0.mlp.down_proj.buf_rounding_opt', 'model.layers.0.mlp.down_proj.buf_scales', …….]”

Does someone have any recommendations on how to perform the inference outside of LLMC? Also, I couldn’t make out the 2-bit quantized version of the model in any of the exported models (fake_quant or transformed). The model weights are always saved in bfloat16 format. How can I access the actual 2-bit weights of the model?

Thanks in advance!

**Comment by Harahan** [comment]
2-bit weights of the model are not supported in the mainstream inference backend. You can refer to our document for exporting the real quantized model.

**Comment by Oehri-Sven** [comment]
Thank you for the quick response. To clarify, does this mean that exporting real quantized models is currently limited to supported inference backends? Specifically, if 2-bit weights are not supported by these backends, it is not possible to export a model with 2-bit weights. Is that correct?

**Comment by Harahan** [comment]
Yes，you are right.

**Comment by brisker** [comment]
请问qwen2-VL-72B的量化校准数据集应该用什么？@Harahan
