### ISSUE TITLE
awq+gptq

### ISSUE THREAD

**Issue by RanchiZhao** [ModelTC/llmc#250]
Hi! Thank you for the solid work.
Are there any configurations available for implementing AWQ w/ GPTQ method in VLMs? Or just use smooth in awq and export the model, w.o. any quantization.

**Comment by chengtao-lv** [comment]
Thanks for your interest!
Sure, you can first perform awq and set **save_trans: True** in config. Then you perform GPTQ and load the previous transformed model.
