### ISSUE TITLE
自定义数据格式什么样的格式

### ISSUE THREAD

**Issue by Harryjun** [ModelTC/llmc#254]
<img width="886" alt="image" src="https://github.com/user-attachments/assets/35c4a20b-8945-4669-84b0-0a2053e7049d">

**Comment by gushiqiao** [comment]
只需要把每个数据放到txt文件每行即可，对于chat模型，要拼好对话模板，例如：
<|user|>\nHello, how are you?</s><|assistant|>\nI'm doing great. How can I help you today?</s><|user|>\nI'd like to show off how chat templating works!</s>
这是一条对话数据，放到txt文件的某一行即可，如果有system prompt，最好也拼到数据里，关于怎么拼对话模板，可以参照https://huggingface.co/docs/transformers/main/chat_templating
