### ISSUE TITLE
使用wanda对Llama-2-7b-hf模型进行压缩，为什么模型大小没有变化？

### ISSUE THREAD

**Issue by ChengShuting** [ModelTC/llmc#30]
config:
base:
    seed: &seed 42
model:
    type: Llama
    path: /data/Llama-2-7b-hf
    torch_dtype: auto
calib:
    name: pileval
    download: True
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: general
    seed: *seed
eval:
    eval_pos: [transformed]
    name: [wikitext2]
    download: True
    path: eval data path
    bs: 1
    seq_len: 2048
sparse:
    method: Wanda
    weight:
        sparsity: 0.5
    sparsity_out: True
save:
    save_fp: False
    save_trans: True
    save_path: ./save3
原模型：
![image](https://github.com/user-attachments/assets/0aaffe3b-01d7-4810-90e7-da91a3bce246)
压缩后：
![image](https://github.com/user-attachments/assets/e364eb6a-d54d-4d10-aa3f-def1d4bf9ff9)

**Comment by Harahan** [comment]
``Wanda`` is an unstructured pruning strategy, which currently brings only theoretical storage savings. You can try the quantization algorithms with ``save_lightllm`` and utilize our [Lightllm](https://github.com/ModelTC/lightllm) for inference.
