### ISSUE TITLE
How to use Tensorrt-LLM as backend

### ISSUE THREAD

**Issue by Worromots** [ModelTC/llmc#5]
as describe in title

**Comment by helloyongyang** [comment]
You can set save_fp in llmc to True. Then you can use trt-llm ammo to convert a naive quant engine.

**Comment by Worromots** [comment]
THX for your reply. I have set save_fp in llmc to True, and these are files saved by llmc, how can I use trt-llm ammo to convert a naive quant engine.
<img width="421" alt="image" src="https://github.com/ModelTC/llmc/assets/49706682/1309bd7a-5d12-47cf-bc58-276fa2d7b47d">

**Comment by Worromots** [comment]
remark，I need your help

**Comment by Harahan** [comment]
The following process needs to modify some codes to change the default settings in TensorRT-LLM. To help users use our tools more conveniently, we are rushing an official doc page about the tool. Please wait for our news patient.
