### ISSUE TITLE
calib config bs=-1:RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 134 but got size 512 for tensor number 1 in the list

### ISSUE THREAD

**Issue by Worromots** [ModelTC/llmc#6]
my calib dataset is c4

It seems that different samples have different lengths and cannot be directly torch.cat(samples, dim=0)。

llmc/llmc/data/dataset/base_dataset.py", line 89, in get_calib_dataset
    batch = torch.cat(samples, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 134 but got size 512 for tensor number 1 in the list

**Comment by helloyongyang** [comment]
Please show me your config
