### ISSUE TITLE
where is run_awq_llama.sh

### ISSUE THREAD

**Issue by LiMa-cas** [ModelTC/llmc#94]

**Comment by llmc-reviewer** [comment]
We have simplified the "run script" and now only keep one: https://github.com/ModelTC/llmc/blob/main/scripts/run_llmc.sh. You can also refer to the documentation(https://llmc-en.readthedocs.io/en/latest/) to run llmc.

**Comment by gushiqiao** [comment]
We have simplified the run script and now only keep one: https://github.com/ModelTC/llmc/blob/main/scripts/run_llmc.sh. You can also refer to the documentation(https://llmc-en.readthedocs.io/en/latest/) to run llmc.
