### ISSUE TITLE
failed to save quantizationed model

### ISSUE THREAD

**Issue by LiMa-cas** [ModelTC/llmc#97]
```
save:
    save_trans: True
    save_lightllm : False
    save_fake: False
    save_path: /extra_data/mali36/llmc/models/
```

when I used the above config, I get a 16G model,
when I used the following config, I get a 29G model, but the AWQ-model is 5G, could u help me ?

```
    save_trans: False
    save_lightllm : True
    save_fake: False
    save_path: /extra_data/mali36/llmc/models/
```

**Comment by gushiqiao** [comment]
save_trans

> ```
> save:
>     save_trans: True
>     save_lightllm : False
>     save_fake: False
>     save_path: /extra_data/mali36/llmc/models/
> ```
> 
> when I used the above config, I get a 16G model, when I used the following config, I get a 29G model, but the AWQ-model is 5G, could u help me ?
> 
> ```
>     save_trans: False
>     save_lightllm : True
>     save_fake: False
>     save_path: /extra_data/mali36/llmc/models/
> ```

The model size saved by save_trans should be the same as the original model size. We are still troubleshooting save_lighllm, so you can first try save_vllm:True and use the vllm engine for inference. You can refer to this document: https://llmc-en.readthedocs.io/en/latest/backend/vllm.html

**Comment by LiMa-cas** [comment]
Hi，I still get the 29G models：

base:
    seed: &seed 42
model:
    type: Llama
    path: /home/test1/workspace/llama3-8B-instruct
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: True
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: True
    seq_len: 1024
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
    # Consistency of tokens between original and fake-quantized model output.
    eval_token_consist: True
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        calib_algo: learnable
    special:
        trans: True
        # The options for "trans_version" include "v1" and "v2".
        # But their results don't differ significantly.
        trans_version: v2
        weight_clip: True
        clip_version: v2
        # For 2-bit quantization, setting "clip_sym: False" will yield better results.
        clip_sym: True
    quant_out: True
save:
    save_vllm : True
    save_path: /home/test1/workspace/llmc/models/

**Comment by llmc-reviewer** [comment]
> Hi，I still get the 29G models：
> 
> base: seed: &seed 42 model: type: Llama path: /home/test1/workspace/llama3-8B-instruct tokenizer_mode: slow torch_dtype: auto calib: name: pileval download: True n_samples: 128 bs: -1 seq_len: 512 preproc: pileval_awq seed: *seed eval: eval_pos: [pretrain, transformed, fake_quant] name: wikitext2 download: True seq_len: 1024 # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False". # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True". bs: 1 inference_per_block: False # Consistency of tokens between original and fake-quantized model output. eval_token_consist: True quant: method: Awq weight: bit: 4 symmetric: True granularity: per_group group_size: 128 calib_algo: learnable special: trans: True # The options for "trans_version" include "v1" and "v2". # But their results don't differ significantly. trans_version: v2 weight_clip: True clip_version: v2 # For 2-bit quantization, setting "clip_sym: False" will yield better results. clip_sym: True quant_out: True save: save_vllm : True save_path: /home/test1/workspace/llmc/models/

This is very strange. Can you show the 'config.json' of the model you saved, as well as your command to count the size of the model?

**Comment by LiMa-cas** [comment]
![{CC173C2A-5EE5-4A7E-9851-ED793C8A2E71}](https://github.com/user-attachments/assets/47cdbb05-9cd1-4ed6-9677-c4db71f6daaa)

**Comment by llmc-reviewer** [comment]
We tried the latest version of llmc, and the size of the save_vllm model we obtained is still 5.4G, and there are only two safetensors. Why don’t you update the version and run it again? It is best to store the model in a new directory

**Comment by LiMa-cas** [comment]
could u show me your yml？

**Comment by llmc-reviewer** [comment]
https://github.com/ModelTC/llmc/blob/main/configs/quantization/backend/vllm/awq_w4a16.yml

**Comment by LiMa-cas** [comment]
could I change the yml like this for awq_w4a16.yml？ add calib_algo: learnable && clip_version: v2 && clip_sym: True
![{B8B995FD-CB60-4816-94DD-2F6CDB839B4E}](https://github.com/user-attachments/assets/bbd5101e-f069-482b-ac2e-7f2f6d5d7902)

**Comment by llmc-reviewer** [comment]
"need_pack" should be specified as True.

**Comment by LiMa-cas** [comment]
Hi，after I got the quantized model，How could I evaluate it？

**Comment by llmc-reviewer** [comment]
To evaluate accuracy, you can use lm_eval：
lm_eval --model vllm \
  --model_args pretrained=".//home/test1/workspace/llmc/models/vllm_quant_model",add_bos_token=true \
  --tasks gsm8k \
  --num_fewshot 5 \
  --limit 250 \
  --batch_size 'auto'

**Comment by LiMa-cas** [comment]
thanks very much！！！

**Comment by LiMa-cas** [comment]
Hi ，I get the awq transformed_model using step_1_awq.yml, but when I used the step_2_omimiq,there are wrong things:
![{1A79FB3A-F359-4C16-A106-00798D1E0DE5}](https://github.com/user-attachments/assets/29c9df42-b4a0-42ec-a6d7-d58c56ab40ea)

**Comment by gushiqiao** [comment]
> Hi ，I get the awq transformed_model using step_1_awq.yml, but when I used the step_2_omimiq,there are wrong things: ![{1A79FB3A-F359-4C16-A106-00798D1E0DE5}](https://private-user-images.githubusercontent.com/80850010/370966131-29c9df42-b4a0-42ec-a6d7-d58c56ab40ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMjExOTUsIm5iZiI6MTcyNzMyMDg5NSwicGF0aCI6Ii84MDg1MDAxMC8zNzA5NjYxMzEtMjljOWRmNDItYjRhMC00MmVjLWE2ZDctZDU4YzU2YWI0MGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAzMjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjgxOTBjOTYxNDA1N2ZlYmIyZjY0MTJkZTY2MTQzODFmMmY0MjcyYmY3OTFlNzRjMmFlOGQyZDNhYjM1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a2VayOZJuBk1nIq0ppKn8DCRkD7fKpM6aj6IHnZiBIY)

please check you 'awq trans' model path

**Comment by LiMa-cas** [comment]
> "need_pack" should be specified as True.

where is to set need_pack?

**Comment by llmc-reviewer** [comment]
https://github.com/ModelTC/llmc/blob/eb66ad6c2f2c526ad2eea8d19710269e7f32e8b3/configs/quantization/backend/vllm/awq_w4a16.yml#L34
